name: Email Action Workflow

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: 23f1000193@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
      - name: Additional verification step
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow completed successfully"
